=== Pierre-HarfangLab/resilient-community-apps/fn_harfanglab_edr/payload_samples/harfanglab_get_endpoint_details/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "group_count": {
          "type": "integer"
        },
        "groups": {
          "type": "array"
        },
        "policy": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "tenant": {},
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "revision": {
              "type": "integer"
            },
            "sleeptime": {
              "type": "integer"
            },
            "sleepjitter": {
              "type": "integer"
            },
            "telemetry_process": {
              "type": "boolean"
            },
            "telemetry_process_limit": {
              "type": "boolean"
            },
            "telemetry_process_limit_value": {
              "type": "integer"
            },
            "telemetry_network": {
              "type": "boolean"
            },
            "telemetry_network_limit": {
              "type": "boolean"
            },
            "telemetry_network_limit_value": {
              "type": "integer"
            },
            "telemetry_log": {
              "type": "boolean"
            },
            "telemetry_log_limit": {
              "type": "boolean"
            },
            "telemetry_log_limit_value": {
              "type": "integer"
            },
            "telemetry_remotethread": {
              "type": "boolean"
            },
            "telemetry_remotethread_limit": {
              "type": "boolean"
            },
            "telemetry_remotethread_limit_value": {
              "type": "integer"
            },
            "telemetry_driverload": {
              "type": "boolean"
            },
            "telemetry_driverload_limit": {
              "type": "boolean"
            },
            "telemetry_driverload_limit_value": {
              "type": "integer"
            },
            "telemetry_alerts_limit": {
              "type": "boolean"
            },
            "telemetry_alerts_limit_value": {
              "type": "integer"
            },
            "binary_download_enabled": {
              "type": "boolean"
            },
            "telemetry_on_alert_enabled": {
              "type": "boolean"
            },
            "telemetry_on_alert_pre_alert_event_count": {
              "type": "integer"
            },
            "telemetry_on_alert_post_alert_max_event_count": {
              "type": "integer"
            },
            "telemetry_on_alert_post_alert_max_duration_secs": {
              "type": "integer"
            },
            "loglevel": {
              "type": "string"
            },
            "use_sigma": {
              "type": "boolean"
            },
            "ioc_mode": {
              "type": "integer"
            },
            "hlai_mode": {
              "type": "integer"
            },
            "hlai_skip_signed_ms": {
              "type": "boolean"
            },
            "hlai_skip_signed_others": {
              "type": "boolean"
            },
            "hlai_minimum_level": {
              "type": "string"
            },
            "hibou_mode": {
              "type": "integer"
            },
            "hibou_skip_signed_ms": {
              "type": "boolean"
            },
            "hibou_skip_signed_others": {
              "type": "boolean"
            },
            "hibou_minimum_level": {
              "type": "string"
            },
            "yara_mode": {
              "type": "integer"
            },
            "yara_skip_signed_ms": {
              "type": "boolean"
            },
            "yara_skip_signed_others": {
              "type": "boolean"
            },
            "use_driver": {
              "type": "boolean"
            },
            "use_isolation": {
              "type": "boolean"
            },
            "use_ransomguard": {
              "type": "boolean"
            },
            "ransomguard_alert_only": {
              "type": "boolean"
            },
            "driverblock_mode": {
              "type": "integer"
            },
            "self_protection": {
              "type": "boolean"
            },
            "audit_killswitch": {
              "type": "boolean"
            },
            "self_protection_feature_hosts": {
              "type": "boolean"
            },
            "feature_callback_tampering": {
              "type": "boolean"
            },
            "use_process_block": {
              "type": "boolean"
            },
            "use_sigma_process_block": {
              "type": "boolean"
            },
            "sigma_ruleset": {},
            "yara_ruleset": {},
            "ioc_ruleset": {}
          }
        },
        "tenant": {},
        "starttime": {
          "type": "string"
        },
        "additional_info": {
          "type": "object",
          "properties": {
            "additional_info1": {},
            "additional_info2": {},
            "additional_info3": {},
            "additional_info4": {}
          }
        },
        "local_user_count": {
          "type": "integer"
        },
        "local_admin_count": {
          "type": "integer"
        },
        "local_group_count": {
          "type": "integer"
        },
        "effective_policy_id": {
          "type": "string"
        },
        "effective_policy_revision": {
          "type": "integer"
        },
        "domainname": {
          "type": "string"
        },
        "dnsdomainname": {},
        "hostname": {
          "type": "string"
        },
        "osmajor": {
          "type": "integer"
        },
        "osminor": {
          "type": "integer"
        },
        "osproducttype": {
          "type": "string"
        },
        "has_valid_password": {
          "type": "boolean"
        },
        "firstseen": {
          "type": "string"
        },
        "lastseen": {
          "type": "string"
        },
        "lastseen_warning": {
          "type": "string"
        },
        "lastseen_error": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "bitness": {
          "type": "string"
        },
        "distroid": {},
        "domain": {},
        "installdate": {
          "type": "string"
        },
        "ipaddress": {
          "type": "string"
        },
        "ipmask": {
          "type": "string"
        },
        "external_ipaddress": {
          "type": "string"
        },
        "osbuild": {
          "type": "integer"
        },
        "osid": {
          "type": "string"
        },
        "ostype": {
          "type": "string"
        },
        "osversion": {
          "type": "string"
        },
        "producttype": {
          "type": "string"
        },
        "servicepack": {},
        "total_memory": {
          "type": "number"
        },
        "cpu_count": {
          "type": "integer"
        },
        "cpu_frequency": {
          "type": "integer"
        },
        "avg_cpu": {
          "type": "number"
        },
        "avg_memory": {
          "type": "number"
        },
        "avg_system_cpu": {
          "type": "number"
        },
        "machine_boottime": {
          "type": "string"
        },
        "isolation_state": {
          "type": "boolean"
        },
        "isolation_policy": {
          "type": "boolean"
        },
        "driver_enabled": {
          "type": "boolean"
        },
        "driver_policy": {
          "type": "boolean"
        },
        "telemetry": {},
        "uninstall_status": {
          "type": "integer"
        },
        "update_status": {
          "type": "integer"
        },
        "update_type": {},
        "refresh_properties_status": {},
        "windows_groups_last_update": {
          "type": "string"
        },
        "windows_users_last_update": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "harfanglab_agent_id": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== Pierre-HarfangLab/resilient-community-apps/fn_harfanglab_edr/payload_samples/harfanglab_get_endpoint_details/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "id": "bab01596-243a-4d57-836a-53c48df074d1",
    "group_count": 0,
    "groups": [],
    "policy": {
      "id": "default_policy_id",
      "tenant": null,
      "name": "default",
      "description": "",
      "revision": 9,
      "sleeptime": 5,
      "sleepjitter": 10,
      "telemetry_process": true,
      "telemetry_process_limit": false,
      "telemetry_process_limit_value": 1000,
      "telemetry_network": true,
      "telemetry_network_limit": false,
      "telemetry_network_limit_value": 1000,
      "telemetry_log": true,
      "telemetry_log_limit": false,
      "telemetry_log_limit_value": 1000,
      "telemetry_remotethread": true,
      "telemetry_remotethread_limit": false,
      "telemetry_remotethread_limit_value": 1000,
      "telemetry_driverload": true,
      "telemetry_driverload_limit": false,
      "telemetry_driverload_limit_value": 1000,
      "telemetry_alerts_limit": false,
      "telemetry_alerts_limit_value": 1000,
      "binary_download_enabled": true,
      "telemetry_on_alert_enabled": true,
      "telemetry_on_alert_pre_alert_event_count": 5000,
      "telemetry_on_alert_post_alert_max_event_count": 5000,
      "telemetry_on_alert_post_alert_max_duration_secs": 600,
      "loglevel": "INFO",
      "use_sigma": true,
      "ioc_mode": 1,
      "hlai_mode": 1,
      "hlai_skip_signed_ms": true,
      "hlai_skip_signed_others": false,
      "hlai_minimum_level": "critical",
      "hibou_mode": 0,
      "hibou_skip_signed_ms": false,
      "hibou_skip_signed_others": false,
      "hibou_minimum_level": "critical",
      "yara_mode": 1,
      "yara_skip_signed_ms": true,
      "yara_skip_signed_others": false,
      "use_driver": true,
      "use_isolation": true,
      "use_ransomguard": true,
      "ransomguard_alert_only": false,
      "driverblock_mode": 1,
      "self_protection": false,
      "audit_killswitch": false,
      "self_protection_feature_hosts": false,
      "feature_callback_tampering": true,
      "use_process_block": true,
      "use_sigma_process_block": false,
      "sigma_ruleset": null,
      "yara_ruleset": null,
      "ioc_ruleset": null
    },
    "tenant": null,
    "starttime": "2023-01-12T07:51:26Z",
    "additional_info": {
      "additional_info1": null,
      "additional_info2": null,
      "additional_info3": null,
      "additional_info4": null
    },
    "local_user_count": 5,
    "local_admin_count": 2,
    "local_group_count": 25,
    "effective_policy_id": "default_policy_id",
    "effective_policy_revision": 9,
    "domainname": "WORKGROUP",
    "dnsdomainname": null,
    "hostname": "WEBSERVER",
    "osmajor": 10,
    "osminor": 0,
    "osproducttype": "Windows Server 2022 Standard Evaluation",
    "has_valid_password": false,
    "firstseen": "2023-01-12T07:51:26.917269Z",
    "lastseen": "2023-02-14T14:33:03.995678Z",
    "lastseen_warning": "2023-02-14T14:33:14.995678Z",
    "lastseen_error": "2023-02-14T14:33:30.995678Z",
    "version": "2.21.0",
    "bitness": "x64",
    "distroid": null,
    "domain": null,
    "installdate": "2023/01/12 07:47:35",
    "ipaddress": "192.168.56.10",
    "ipmask": "255.255.255.0",
    "external_ipaddress": "10.42.0.227",
    "osbuild": 20348,
    "osid": "00454-40000-00001-AA958",
    "ostype": "windows",
    "osversion": "10.0.20348",
    "producttype": "server",
    "servicepack": null,
    "total_memory": 2133962752.0,
    "cpu_count": 2,
    "cpu_frequency": 3191,
    "avg_cpu": 0.7,
    "avg_memory": 192022118.0,
    "avg_system_cpu": 12.7,
    "machine_boottime": "2023-01-12T07:25:12Z",
    "isolation_state": false,
    "isolation_policy": false,
    "driver_enabled": true,
    "driver_policy": false,
    "telemetry": null,
    "uninstall_status": 0,
    "update_status": 0,
    "update_type": null,
    "refresh_properties_status": null,
    "windows_groups_last_update": "2023-02-14T13:36:52.830718Z",
    "windows_users_last_update": "2023-02-14T13:36:52.830725Z",
    "status": "online"
  },
  "raw": null,
  "inputs": {
    "harfanglab_agent_id": "bab01596-243a-4d57-836a-53c48df074d1"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-harfanglab-edr",
    "package_version": "1.0.0",
    "host": "tui",
    "execution_time_ms": 182,
    "timestamp": "2023-02-14 15:33:04"
  }
}
