=== Pierre-HarfangLab/resilient-community-apps/fn_harfanglab_edr/payload_samples/harfanglab_add_ioc_to_source/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {},
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "harfanglab_source_name": {
          "type": "string"
        },
        "harfanglab_ioc_value": {
          "type": "string"
        },
        "harfanglab_ioc_status": {
          "type": "string"
        },
        "harfanglab_ioc_comment": {
          "type": "string"
        },
        "harfanglab_ioc_type": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== Pierre-HarfangLab/resilient-community-apps/fn_harfanglab_edr/payload_samples/harfanglab_telemetry_search_destination_ip/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "message": "OK",
    "markdown": "### IP search\n\n#### Search details\n\n|Ip|Limit|Search Type|Total Number Of Hits|Investigation Link|\n|---|---|---|---|---|\n| 10.1.1.222 | 10 | searchDestinationIP | 28126 | https://<your stack>:8443/telemetry/network-connections?offset=0&daddr=10.1.1.222&limit=10&ordering=-event_create_date |\n#### Results (fetched 10/28126 entries)\n\n|Creation Date|Hostname|Image Name|Username|Source Address|Source Port|Destination Address|Destination Port|Direction|\n|---|---|---|---|---|---|---|---|---|\n| 2023-02-14T14:12:30.804000Z | WORKSTATION-3752 | C:\\Users\\Public\\svchost.exe | WORKSTATION-375\\vagrant | 192.168.56.200 | 50060 | 10.1.1.222 | 80 | out |\n| 2023-02-14T14:10:48.161000Z | WORKSTATION-3752 | C:\\Users\\Public\\svchost.exe | WORKSTATION-375\\vagrant | 192.168.56.200 | 50059 | 10.1.1.222 | 80 | out |\n| 2023-02-14T14:09:05.493000Z | WORKSTATION-3752 | C:\\Users\\Public\\svchost.exe | WORKSTATION-375\\vagrant | 192.168.56.200 | 50058 | 10.1.1.222 | 80 | out |\n| 2023-02-14T14:07:22.723000Z | WORKSTATION-3752 | C:\\Users\\Public\\svchost.exe | WORKSTATION-375\\vagrant | 192.168.56.200 | 50057 | 10.1.1.222 | 80 | out |\n| 2023-02-14T14:05:39.988000Z | WORKSTATION-3752 | C:\\Users\\Public\\svchost.exe | WORKSTATION-375\\vagrant | 192.168.56.200 | 50056 | 10.1.1.222 | 80 | out |\n| 2023-02-14T14:03:57.275000Z | WORKSTATION-3752 | C:\\Users\\Public\\svchost.exe | WORKSTATION-375\\vagrant | 192.168.56.200 | 50055 | 10.1.1.222 | 80 | out |\n| 2023-02-14T14:02:14.595000Z | WORKSTATION-3752 | C:\\Users\\Public\\svchost.exe | WORKSTATION-375\\vagrant | 192.168.56.200 | 50050 | 10.1.1.222 | 80 | out |\n| 2023-02-14T14:00:31.925000Z | WORKSTATION-3752 | C:\\Users\\Public\\svchost.exe | WORKSTATION-375\\vagrant | 192.168.56.200 | 50049 | 10.1.1.222 | 80 | out |\n| 2023-02-14T13:58:49.300000Z | WORKSTATION-3752 | C:\\Users\\Public\\svchost.exe | WORKSTATION-375\\vagrant | 192.168.56.200 | 50048 | 10.1.1.222 | 80 | out |\n| 2023-02-14T13:57:06.650000Z | WORKSTATION-3752 | C:\\Users\\Public\\svchost.exe | WORKSTATION-375\\vagrant | 192.168.56.200 | 50046 | 10.1.1.222 | 80 | out |\n",
    "search_type": "searchDestinationIP",
    "args": {
      "ip": "10.1.1.222",
      "limit": 10
    },
    "title": "IP search",
    "output": [
      {
        "creation date": "2023-02-14T14:12:30.804000Z",
        "hostname": "WORKSTATION-3752",
        "image name": "C:\\Users\\Public\\svchost.exe",
        "username": "WORKSTATION-375\\vagrant",
        "source address": "192.168.56.200",
        "source port": 50060,
        "destination address": "10.1.1.222",
        "destination port": 80,
        "direction": "out"
      },
      {
        "creation date": "2023-02-14T14:10:48.161000Z",
        "hostname": "WORKSTATION-3752",
        "image name": "C:\\Users\\Public\\svchost.exe",
        "username": "WORKSTATION-375\\vagrant",
        "source address": "192.168.56.200",
        "source port": 50059,
        "destination address": "10.1.1.222",
        "destination port": 80,
        "direction": "out"
      },
      {
        "creation date": "2023-02-14T14:09:05.493000Z",
        "hostname": "WORKSTATION-3752",
        "image name": "C:\\Users\\Public\\svchost.exe",
        "username": "WORKSTATION-375\\vagrant",
        "source address": "192.168.56.200",
        "source port": 50058,
        "destination address": "10.1.1.222",
        "destination port": 80,
        "direction": "out"
      },
      {
        "creation date": "2023-02-14T14:07:22.723000Z",
        "hostname": "WORKSTATION-3752",
        "image name": "C:\\Users\\Public\\svchost.exe",
        "username": "WORKSTATION-375\\vagrant",
        "source address": "192.168.56.200",
        "source port": 50057,
        "destination address": "10.1.1.222",
        "destination port": 80,
        "direction": "out"
      },
      {
        "creation date": "2023-02-14T14:05:39.988000Z",
        "hostname": "WORKSTATION-3752",
        "image name": "C:\\Users\\Public\\svchost.exe",
        "username": "WORKSTATION-375\\vagrant",
        "source address": "192.168.56.200",
        "source port": 50056,
        "destination address": "10.1.1.222",
        "destination port": 80,
        "direction": "out"
      },
      {
        "creation date": "2023-02-14T14:03:57.275000Z",
        "hostname": "WORKSTATION-3752",
        "image name": "C:\\Users\\Public\\svchost.exe",
        "username": "WORKSTATION-375\\vagrant",
        "source address": "192.168.56.200",
        "source port": 50055,
        "destination address": "10.1.1.222",
        "destination port": 80,
        "direction": "out"
      },
      {
        "creation date": "2023-02-14T14:02:14.595000Z",
        "hostname": "WORKSTATION-3752",
        "image name": "C:\\Users\\Public\\svchost.exe",
        "username": "WORKSTATION-375\\vagrant",
        "source address": "192.168.56.200",
        "source port": 50050,
        "destination address": "10.1.1.222",
        "destination port": 80,
        "direction": "out"
      },
      {
        "creation date": "2023-02-14T14:00:31.925000Z",
        "hostname": "WORKSTATION-3752",
        "image name": "C:\\Users\\Public\\svchost.exe",
        "username": "WORKSTATION-375\\vagrant",
        "source address": "192.168.56.200",
        "source port": 50049,
        "destination address": "10.1.1.222",
        "destination port": 80,
        "direction": "out"
      },
      {
        "creation date": "2023-02-14T13:58:49.300000Z",
        "hostname": "WORKSTATION-3752",
        "image name": "C:\\Users\\Public\\svchost.exe",
        "username": "WORKSTATION-375\\vagrant",
        "source address": "192.168.56.200",
        "source port": 50048,
        "destination address": "10.1.1.222",
        "destination port": 80,
        "direction": "out"
      },
      {
        "creation date": "2023-02-14T13:57:06.650000Z",
        "hostname": "WORKSTATION-3752",
        "image name": "C:\\Users\\Public\\svchost.exe",
        "username": "WORKSTATION-375\\vagrant",
        "source address": "192.168.56.200",
        "source port": 50046,
        "destination address": "10.1.1.222",
        "destination port": 80,
        "direction": "out"
      }
    ],
    "count": 28126,
    "link": "https://<your stack>:8443/telemetry/network-connections?offset=0&daddr=10.1.1.222&limit=10&ordering=-event_create_date"
  },
  "raw": null,
  "inputs": {
    "harfanglab_ip": "10.1.1.222",
    "harfanglab_limit": 10
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-harfanglab-edr",
    "package_version": "1.0.0",
    "host": "tui",
    "execution_time_ms": 124,
    "timestamp": "2023-02-14 15:13:26"
  }
}

=== Pierre-HarfangLab/resilient-community-apps/fn_harfanglab_edr/payload_samples/harfanglab_add_ioc_to_source/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": null,
  "raw": null,
  "inputs": {
    "harfanglab_source_name": "Test",
    "harfanglab_ioc_value": "73c1c74eca4dbf5a234f558aa9c35bd9d7a24bf692ebf830822c97a33341ad28",
    "harfanglab_ioc_status": "testing",
    "harfanglab_ioc_comment": "",
    "harfanglab_ioc_type": "hash"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-harfanglab-edr",
    "package_version": "1.0.0",
    "host": "tui",
    "execution_time_ms": 186,
    "timestamp": "2023-02-14 15:11:05"
  }
}

=== Pierre-HarfangLab/resilient-community-apps/fn_harfanglab_edr/payload_samples/harfanglab_unisolate_endpoint/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": "Host bab01596-243a-4d57-836a-53c48df074d1 successfully unisolated",
  "raw": null,
  "inputs": {
    "harfanglab_agent_id": "bab01596-243a-4d57-836a-53c48df074d1"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-harfanglab-edr",
    "package_version": "1.0.0",
    "host": "tui",
    "execution_time_ms": 8879,
    "timestamp": "2023-02-14 15:32:49"
  }
}
