=== Pierre-HarfangLab/resilient-community-apps/fn_harfanglab_edr/payload_samples/harfanglab_run_job/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "markdown": {
          "type": "string"
        },
        "output": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "session": {
                "type": "integer"
              },
              "username": {
                "type": "string"
              },
              "integrity": {
                "type": "string"
              },
              "pid": {
                "type": "integer"
              },
              "ppid": {
                "type": "integer"
              },
              "cmdline": {
                "type": "string"
              },
              "fullpath": {
                "type": [
                  "null",
                  "string"
                ]
              },
              "signed": {
                "type": "boolean"
              },
              "md5": {
                "type": [
                  "null",
                  "string"
                ]
              },
              "sha1": {
                "type": [
                  "null",
                  "string"
                ]
              },
              "sha256": {
                "type": [
                  "null",
                  "string"
                ]
              }
            }
          }
        },
        "title": {
          "type": "string"
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "harfanglab_job_name": {
          "type": "string"
        },
        "harfanglab_agent_id": {
          "type": "string"
        },
        "harfanglab_job_timeout": {
          "type": "integer"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== Pierre-HarfangLab/resilient-community-apps/fn_harfanglab_edr/payload_samples/harfanglab_run_job/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "message": "OK",
    "markdown": "### Process list\n|Name|Session|Username|Integrity|Pid|Ppid|Cmdline|Fullpath|Signed|Md5|Sha1|Sha256|\n|---|---|---|---|---|---|---|---|---|---|---|---|\n| AggregatorHost.exe | 0 | NT AUTHORITY\\SYSTEM | System | 2524 | 936 | AggregatorHost.exe | C:\\Windows\\System32\\AggregatorHost.exe | True | 391ed483154f77cfdad1e2e0f9ce2001 | 12fc5a711e2be5b64f6b9e2097f21d9020340708 | 6b388c39bdf2f7827b7b2287db82c9fd62e42a588f85a0bbe97ceedf4a452fc4 |\n| conhost.exe | 0 | NT AUTHORITY\\SYSTEM | System | 376 | 4344 | \\??\\C:\\Windows\\system32\\conhost.exe 0x4 | C:\\Windows\\System32\\conhost.exe | True | b03d74d481d9d64047625bec2d64a0ce | 4f1e9d9c9624298620312005cb218a9905c7690c | 6b481d656414c50d8bd0bedcd615aeaf2f5f68576cb6732a9548e0da87729733 |\n| csrss.exe | 0 | NT AUTHORITY\\SYSTEM | Unknown | 428 | 420 | %SystemRoot%\\system32\\csrss.exe ObjectDirectory=\\Windows SharedSection=1024,20480,768 Windows=On SubSystemType=Windows ServerDll=basesrv,1 ServerDll=winsrv:UserServerDllInitialization,3 ServerDll=sxssrv,4 ProfileControl=Off MaxRequestThreads=16 | C:\\Windows\\System32\\csrss.exe | True | a6c9ee45bff7c5e696b07ec41af84541 | 7821fb14835083bae87a66ce96b67b261bea6b2b | 50cbdbce85014f1042f99d5acdaad88ff268317a605bc3700b2487edd0f2ef0e |\n| csrss.exe | 1 | NT AUTHORITY\\SYSTEM | Unknown | 512 | 488 | %SystemRoot%\\system32\\csrss.exe ObjectDirectory=\\Windows SharedSection=1024,20480,768 Windows=On SubSystemType=Windows ServerDll=basesrv,1 ServerDll=winsrv:UserServerDllInitialization,3 ServerDll=sxssrv,4 ProfileControl=Off MaxRequestThreads=16 | C:\\Windows\\System32\\csrss.exe | True | a6c9ee45bff7c5e696b07ec41af84541 | 7821fb14835083bae87a66ce96b67b261bea6b2b | 50cbdbce85014f1042f99d5acdaad88ff268317a605bc3700b2487edd0f2ef0e |\n| ctfmon.exe | 1 | WEBSERVER\\vagrant | High | 2784 | 580 | ctfmon.exe | C:\\Windows\\System32\\ctfmon.exe | True | 91e5e0722b281024e60d5768ab948794 | 59672c3f95d6897a60de38391843c621ef5c66c8 | 2d0ba4fd142dd53f0cd1efbd3f09f2514df8f541ed4df27fdbc25073a8f3240e |\n| dwm.exe | 1 | Window Manager\\DWM-1 | System | 960 | 584 | dwm.exe | C:\\Windows\\System32\\dwm.exe | True | 66f552d20dcf3377279c20a119e0e72f | 74704b48412bd7c3f1aee895b6fa78a192b772cc | 644a42249d70082aa3d5e132cffa213c30547a02cf89ed688a3c4550c496109d |\n| explorer.exe | 1 | WEBSERVER\\vagrant | High | 2444 | 2188 | C:\\Windows\\Explorer.EXE | C:\\Windows\\explorer.exe | True | 7761d5917fa1adc297a5ce0cf1e242eb | dbe123d35922cdfe3eba25d197bbe44b84a47e0d | a3c36c8481af88a925bff1bb0283c028b531e1dc1167d279186a046091bf37ce |\n| fontdrvhost.exe | 1 | Font Driver Host\\UMFD-1 | Low | 768 | 584 | fontdrvhost.exe | C:\\Windows\\System32\\fontdrvhost.exe | True | dd24bac3913d47f9b35a8718aeed3cbe | 01c21d757a5668d372e711103e3a2c0f1edfe858 | 7783c67ed771fcb500f3f58cf19d5e876b7698a4584b402739c79dab260008b7 |\n| fontdrvhost.exe | 0 | Font Driver Host\\UMFD-0 | Low | 776 | 496 | fontdrvhost.exe | C:\\Windows\\System32\\fontdrvhost.exe | True | dd24bac3913d47f9b35a8718aeed3cbe | 01c21d757a5668d372e711103e3a2c0f1edfe858 | 7783c67ed771fcb500f3f58cf19d5e876b7698a4584b402739c79dab260008b7 |\n| hurukai.exe | 0 | NT AUTHORITY\\SYSTEM | System | 508 | 628 | C:\\Program Files\\HarfangLab\\hurukai.exe | C:\\Program Files\\HarfangLab\\hurukai.exe | True | c02cfc2d2e6b73d551bc570fe5c0e621 | 747b868d53396e936a7e4b0a33e5b3062b04423e | ec3a510c206f4390856ae1151113e54603277e80eb36bbfec1bd9ad6a92cce34 |\n| hurukai.exe | 0 | NT AUTHORITY\\SYSTEM | System | 4344 | 508 | C:\\Program Files\\HarfangLab\\hurukai.exe {ea566d09-a9cd-78b9-4d2d-b9963208e733} | C:\\Program Files\\HarfangLab\\hurukai.exe | True | c02cfc2d2e6b73d551bc570fe5c0e621 | 747b868d53396e936a7e4b0a33e5b3062b04423e | ec3a510c206f4390856ae1151113e54603277e80eb36bbfec1bd9ad6a92cce34 |\n| lsass.exe | 0 | NT AUTHORITY\\SYSTEM | System | 640 | 496 | C:\\Windows\\system32\\lsass.exe | C:\\Windows\\System32\\lsass.exe | True | 6da2fcc580c720c16612057e83f47f04 | 66d61b2c69a5797f0d01adaa179b123d6e12ad8d | 3a5c6719ef2e4df699cd27f8dff09b51dbeae395701b18c2b7f990f829e6ca6a |\n| msdtc.exe | 0 | NT AUTHORITY\\NETWORK SERVICE | System | 2960 | 628 | C:\\Windows\\System32\\msdtc.exe | C:\\Windows\\System32\\msdtc.exe | True | bd7be47340ba4888b9b47ad323ff51d3 | 457c91e5cf090a43b51964024bcd21e5525574e7 | ee84158da9a863daa633092f691761952de7888af01fd8020761cfd232e3bc88 |\n| MsMpEng.exe | 0 | NT AUTHORITY\\SYSTEM | Unknown | 4888 | 628 | C:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\4.18.2211.5-0\\MsMpEng.exe | C:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\4.18.2211.5-0\\MsMpEng.exe | True | 0ce4761bf8ceca34a907580d156f74b9 | dfdb9afc3f73b1f3b7f116e581a99d9f64fb9fa3 | 9ad63a5ce2cbce512bd960f6f4e69c23c68c38378d759d4ac1fb5c5916ad044c |\n| Registry | 0 | NT AUTHORITY\\SYSTEM | Unknown | 100 | 4 |  | registry | False |  |  |  |\n| RuntimeBroker.exe | 1 | WEBSERVER\\vagrant | High | 2840 | 752 | C:\\Windows\\System32\\RuntimeBroker.exe -Embedding | C:\\Windows\\System32\\RuntimeBroker.exe | True | 1541969ef9db9aae4e89b749d427cdea | 732f62280a77b9e2337a799deee4089145da9a09 | 91932960c0ed923cc0204b3661b4807bbdc314c6652ea7e6016d96ce36c5d765 |\n| RuntimeBroker.exe | 1 | WEBSERVER\\vagrant | High | 3460 | 752 | C:\\Windows\\System32\\RuntimeBroker.exe -Embedding | C:\\Windows\\System32\\RuntimeBroker.exe | True | 1541969ef9db9aae4e89b749d427cdea | 732f62280a77b9e2337a799deee4089145da9a09 | 91932960c0ed923cc0204b3661b4807bbdc314c6652ea7e6016d96ce36c5d765 |\n| RuntimeBroker.exe | 1 | WEBSERVER\\vagrant | High | 4580 | 752 | C:\\Windows\\System32\\RuntimeBroker.exe -Embedding | C:\\Windows\\System32\\RuntimeBroker.exe | True | 1541969ef9db9aae4e89b749d427cdea | 732f62280a77b9e2337a799deee4089145da9a09 | 91932960c0ed923cc0204b3661b4807bbdc314c6652ea7e6016d96ce36c5d765 |\n| RuntimeBroker.exe | 1 | WEBSERVER\\vagrant | High | 5100 | 752 | C:\\Windows\\System32\\RuntimeBroker.exe -Embedding | C:\\Windows\\System32\\RuntimeBroker.exe | True | 1541969ef9db9aae4e89b749d427cdea | 732f62280a77b9e2337a799deee4089145da9a09 | 91932960c0ed923cc0204b3661b4807bbdc314c6652ea7e6016d96ce36c5d765 |\n| SearchApp.exe | 1 | WEBSERVER\\vagrant | Low | 3204 | 752 | C:\\Windows\\SystemApps\\Microsoft.Windows.Search_cw5n1h2txyewy\\SearchApp.exe -ServerName:CortanaUI.AppX8z9r6jm96hw4bsbneegw0kyxx296wr9t.mca | C:\\Windows\\SystemApps\\Microsoft.Windows.Search_cw5n1h2txyewy\\SearchApp.exe | True | efde01e2986731e39c1c2e0f5a1dbd06 | 0a3a0bcff288a50a567945eb5ec0946435ee72f0 | b0a7de8ebb79a793dfcede37000d6ee614fbbd31ec0241bba58604350e37168f |\n| SecurityHealthService.exe | 0 | NT AUTHORITY\\SYSTEM | Unknown | 2904 | 628 | C:\\Windows\\system32\\SecurityHealthService.exe | C:\\Windows\\System32\\SecurityHealthService.exe | True | ed5777a65aca7fdb2cf1c97a8641a6e6 | 8dc3a49c00f9409ba185329152dafa3201742b17 | 0459a49b6cce70f0532af5a6c41a965d79a55d33fb590e71db55aa82cade038f |\n| services.exe | 0 | NT AUTHORITY\\SYSTEM | Unknown | 628 | 496 | C:\\Windows\\system32\\services.exe | C:\\Windows\\System32\\services.exe | True | 042c0e965c5db03dbf911e4c6a319ce8 | 2d3b9ae599f6b525ffbd3087060a5c210cc86f8a | 711f6ac28ccf2b6d3976bd4529a55ec38ac8c8e6f2376f5b2dcb41a091e28cc2 |\n| ShellExperienceHost.exe | 1 | WEBSERVER\\vagrant | Low | 4440 | 752 | C:\\Windows\\SystemApps\\ShellExperienceHost_cw5n1h2txyewy\\ShellExperienceHost.exe -ServerName:App.AppXtk181tbxbce2qsex02s8tw7hfxa9xb3t.mca | C:\\Windows\\SystemApps\\ShellExperienceHost_cw5n1h2txyewy\\ShellExperienceHost.exe | True | 490512224d6a82112eadf607a60bb798 | 5132006107f82835076a58dacb032599eb62061b | eee13d00b534c1cdc72427d8a73a88755889f03d87936ce058b7644bf9500408 |\n| sihost.exe | 1 | WEBSERVER\\vagrant | High | 2952 | 1300 | sihost.exe | C:\\Windows\\System32\\sihost.exe | True | 45cfb07366fe59573369e66029b12cea | 6fc5f3fc05c987c75b44c5936e89d319ffe714ba | 98b93560ef621b0943d66057aec90b90d47b007a03cfe6b11acf88d6aea67ecd |\n| smss.exe | 0 | NT AUTHORITY\\SYSTEM | Unknown | 332 | 4 | \\SystemRoot\\System32\\smss.exe | C:\\Windows\\System32\\smss.exe | True | 44962fd12f0d29b0713bb5e14653194a | 3b2af5ef58ecf86abe51a730493363448b95dd0a | d94c6656d377bb43a5cca307fc46f5de2b259e8884acedddf0b07f45425f457e |\n| spoolsv.exe | 0 | NT AUTHORITY\\SYSTEM | System | 2028 | 628 | C:\\Windows\\System32\\spoolsv.exe | C:\\Windows\\System32\\spoolsv.exe | True | 55bb3facc6ef795f6f1d8cc656bcb779 | a5f5041642567e2f461c3c9c849e2c04b6e062ae | e05baa5e9f6153043400b4db0c5a63b4d802bd76169f8a6ac111b3f5def8ab94 |\n| sshd.exe | 0 | NT AUTHORITY\\SYSTEM | System | 1664 | 628 | C:\\Program Files\\OpenSSH-Win64\\sshd.exe | C:\\Program Files\\OpenSSH-Win64\\sshd.exe | True | 331ba0e529810ef718dd3efbd1242302 | 631244d731f406394c17c7dfd85203e317c74814 | e6a972f9db27de18be225095b3b3141b945be8aadc4014c8704ae5acafe3e8e0 |\n| StartMenuExperienceHost.exe | 1 | WEBSERVER\\vagrant | Low | 4036 | 752 | C:\\Windows\\SystemApps\\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\\StartMenuExperienceHost.exe -ServerName:App.AppXywbrabmsek0gm3tkwpr5kwzbs55tkqay.mca | C:\\Windows\\SystemApps\\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\\StartMenuExperienceHost.exe | True | c6b9db31748cf4bf854639dd55d6f45b | 4c74b85b43c5e5c45a4c24ccd98c26f6eb0ed854 | 64beeb8e8d9ea770e9edbe3f9478cdfd68a3130710cbef6429a202b45b63312a |\n| svchost.exe | 0 | NT AUTHORITY\\NETWORK SERVICE | System | 2740 | 628 | C:\\Windows\\system32\\svchost.exe -k NetworkServiceNetworkRestricted -p | C:\\Windows\\System32\\svchost.exe | True | dc32aba4669eafb22fcacd5ec836a107 | da7a6e7798d448cd593b11735e2b614ec2b75b29 | 31780ff2aaf7bc71f755ba0e4fef1d61b060d1d2741eafb33cbab44d889595a0 |\n| svchost.exe | 0 | NT AUTHORITY\\NETWORK SERVICE | System | 388 | 628 | C:\\Windows\\System32\\svchost.exe -k termsvcs | C:\\Windows\\System32\\svchost.exe | True | dc32aba4669eafb22fcacd5ec836a107 | da7a6e7798d448cd593b11735e2b614ec2b75b29 | 31780ff2aaf7bc71f755ba0e4fef1d61b060d1d2741eafb3
